# SPDX-License-Identifier: CC0-1.0
#
# Copyright 2021 Simon Marynissen <marynissen.simon@gmail.com>

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '01:23'
    commit-message:
      prefix: ci
