# SPDX-License-Identifier: CC0-1.0
#
# Copyright 2021 Simon Marynissen <marynissen.simon@gmail.com>

branches: main
repositoryUrl: 'git@github.com:oricad/test.git'
plugins:
  - - '@semantic-release/commit-analyzer'
    - parserOpts:
      noteKeywords:
        - 'BREAKING CHANGE'
        - 'BREAKING CHANGES'
        - 'BREAKING'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - assets:
      - dist/oricad*.deb
  - - '@semantic-release/git'
    - assets:
      - VERSION
      - docs/CHANGELOG.md
      message: 'chore(release): ${nextRelease.gitTag}\n\n${nextRelease.notes}'
#    - assets:
#      - docs/CHANGELOG.md
#    - message: 'chore(release): v${nextRelease.version}\n\n${nextRelease.notes}'
  - - '@semantic-release/changelog'
    - changelogTitle: '# Changelog'
      changelogFile: docs/CHANGELOG.md
  - - '@semantic-release/exec'
    - prepareCmd: 'scripts/set-version.sh ${nextRelease.version}'
preset: conventionalcommits

analyzeCommits:
  releaseRules:
    - breaking: true
      release: major
    - revert: true
      release: patch
    - type: style
      release: patch
    - type: refactor
      release: minor
    - type: perf
      release: patch
    - type: fix
      release: patch
    - type: feat
      release: minor
    - type: docs
      release: false
    - type: test
      release: false
    - type: security
      release: minor
    - type: ci
      release: patch
    - type: build
      release: patch
    - type: i18n
      release: patch
    - type: typo
      release: patch
    - type: chore
      release: patch
    - type: license
      release: false
generateNotes:
  writerOpts:
    title: Changelog
    groupBy: type
    commitGroupsSort:
      - feat
      - fix
      - perf
      - security
      - i18n
    commitsSort:
      - subject
      - scope

presetConfig:
  types:
    - type: style
      section: Improving style
      hidden: true
    - type: refactor
      section: Refactoring code
      hidden: true
    - type: perf
      section: Performance fixes
    - type: fix
      section: Bug fixes
    - type: feat
      section: Features
    - type: docs
      section: Documentation
      hidden: true
    - type: test
      section: Adding tests
      hidden: true
    - type: security
      section: Security
    - type: ci
      section: Continuous integration
      hidden: true
    - type: build
      section: Changes to build system
      hidden: true
    - type: i18n
      section: Internationalization and localization
    - type: typo
      section: Fixing a typo
      hidden: true
    - type: chore
      section: Used for chores, usually automated
      hidden: true
    - type: license
      section: License information
      hidden: true

