name: Build and test
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oricad/oricad-dev:ubuntu-20.04
      volumes:
        - ${{ github.workspace }}:/oricad
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          cmake -GNinja -S. -Bbuild \
          && cmake --build build --target all \
          && cd build \
          && ctest
