name: Build and test
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: echo "Installing"
      - name: Install Ninja
        run: sudo apt-get install -y ninja-build
      - name: Build
        run: |
          cmake -GNinja -DCMAKE_BUILD_TYPE:String=Debug
