name: Build and test
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04]
    container:
      image: oricad/oricad-dev:${{ matrix.os }}
      volumes:
        - ${{ github.workspace }}:/oricad
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          cmake -GNinja -S. -Bbuild \
          && cmake --build build --target all
      - name: test
        run: |
          cd build && ctest
