name: Build and test
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: echo "Installing"
      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build
      - name: Install Microsoft GSL
        run: |
          "${VCPKG_INSTALLATION_ROOT}"/vcpkg integrate install \
          && "${VCPKG_INSTALLATION_ROOT}"/vcpkg install ms-gsl
      - name: Install Qt
        run: sudo apt-get update && sudo apt-get install -y qtdeclarative5-dev
      - name: Check env
        run: env
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build
        run: |
          cmake -GNinja -DCMAKE_BUILD_TYPE:String=Debug -DCMAKE_PREFIX_PATH="${VCPKG_INSTALLATION_ROOT}/installed/x64-linux"
