name: static-checks
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: REUSE compliance
        uses: fsfe/reuse-action@v1
